# Generated by Django 4.2.30 on 2026-05-22 06:20

import agency.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-deal_date'], 'permissions': [('view_own_deal', 'Просмотр своих сделок'), ('add_own_deal', 'Оформление своих сделок'), ('change_own_deal', 'Изменение своих сделок')], 'verbose_name': 'Сделка', 'verbose_name_plural': 'Сделки'},
        ),
        migrations.AddField(
            model_name='buyer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='full_name',
            field=models.CharField(max_length=200, validators=[agency.validators.validate_non_whitespace], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[agency.validators.validate_positive_decimal], verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='full_name',
            field=models.CharField(max_length=200, validators=[agency.validators.validate_non_whitespace], verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='description',
            field=models.TextField(validators=[agency.validators.validate_non_whitespace], verbose_name='Описание типа'),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='name',
            field=models.CharField(max_length=100, validators=[agency.validators.validate_non_whitespace], verbose_name='Название типа'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='address',
            field=models.CharField(max_length=300, validators=[agency.validators.validate_non_whitespace], verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[agency.validators.validate_positive_decimal], verbose_name='Площадь, м²'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='code',
            field=models.CharField(max_length=50, unique=True, validators=[agency.validators.validate_non_whitespace], verbose_name='Код объекта'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14, validators=[agency.validators.validate_positive_decimal], verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='title',
            field=models.CharField(max_length=200, validators=[agency.validators.validate_non_whitespace], verbose_name='Заголовок'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('client', 'Клиент'), ('employee', 'Сотрудник')], default='client', max_length=20, verbose_name='Роль')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
