# Generated by Django 4.2.30 on 2026-05-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_alter_deal_options_buyer_user_alter_buyer_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(blank=True, default='Europe/Minsk', help_text='IANA, например Europe/Minsk', max_length=63, verbose_name='Часовой пояс'),
        ),
    ]
